name: Publish Dart Package

on:
  push:
    branches: [ pub ]
  pull_request:
    branches: [ pub ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    # - name: Run tests
      # run: pub run test
    - name: pub publish ğŸ¯
      run: pub publish
